spring.application.name=test-delivery

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=PostgreSQL

spring.docker.compose.enabled=false

#swagger
springdoc.swagger-ui.url=/openapi.yaml



